### ISSUE TITLE
problem with default rpc endpoint

### ISSUE THREAD

**Issue by breign** [unwriter/B#2]
If I set `pay.rpc: "https://bitcoinsv.si"` datapay lib returns error NodeError.

I'm a node noob, how can I debug || what must I setup on my end so I can replace default rpc on https://bchsvexplorer.com ?

**Comment by unwriter** [comment]
@breign Could you open an issue on the datapay repository, along with the simplest possible replicable code and the full error message? 

Here's datapay issues link: https://github.com/unwriter/datapay/issues
